---
- name: "Install default Apache Web Server"
  hosts: my_host
  become: yes 

  tasks:
   - name: Install Apache Web erver
     apt: name=nginx-full state=latest

   - name: Start and enable Apache Web Server
     service: name=nginx state=started enabled=no
