---
- name: My Paper and Vars
  hosts: my_host
  become: yes

  vars:
   message1: Hellow
   message2: World!
   secret: CNGJFHTF

  tasks:
   - name: Hi Secret
     debug:
       var: secret

   - name: Print 2 var
     debug:
       msg: "My secret is: {{ secret }} "
   
   - set_fact: 
        full_message={{ message1 }} {{ message2 }} from {{ owner }}
   - debug:
        var: full_message
   
   - debug:
        var: ansible_distribution


   - shell:
           uptime
     register: result
   - debug:
           # var: result
           var: result.stdout

